import { TradeModel, TradeSide } from '../models';

export const trades: TradeModel[] = [
  {
    symbol: 'BTC',
    base: 'USDT',
    amount: 0.2196,
    atPrice: 9358,
    side: TradeSide.Buy,
  },
  {
    symbol: 'BTC',
    base: 'USDT',
    amount: 0.01,
    atPrice: 11107.95,
    side: TradeSide.Buy,
  },
  {
    symbol: 'IOTA',
    base: 'USDT',
    amount: 662.26,
    atPrice: 0.3035,
    side: TradeSide.Buy,
  },
  {
    symbol: 'XTZ',
    base: 'USDT',
    amount: 139,
    atPrice: 2.8754,
    side: TradeSide.Buy,
  },
  {
    symbol: 'BNB',
    base: 'USDT',
    amount: 18.89,
    atPrice: 21.1392,
    side: TradeSide.Buy,
  },
  {
    symbol: 'BNB',
    base: 'USDT',
    amount: 18.89,
    atPrice: 23.5,
    side: TradeSide.Sell,
  },
  {
    symbol: 'BTC',
    base: 'USDT',
    amount: 0.162885,
    atPrice: 11594,
    side: TradeSide.Buy,
  },
  {
    symbol: 'TRX',
    base: 'USDT',
    amount: 1000,
    atPrice: 0.02032,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 255,
    atPrice: 0.4025,
    side: TradeSide.Buy,
  },
  {
    symbol: 'XLM',
    base: 'USDT',
    amount: 501,
    atPrice: 0.10321,
    side: TradeSide.Buy,
  },
  {
    symbol: 'ENJ',
    base: 'USDT',
    amount: 200,
    atPrice: 0.20909,
    side: TradeSide.Buy,
  },
  {
    symbol: 'XRP',
    base: 'USDT',
    amount: 839,
    atPrice: 0.29781,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 61,
    atPrice: 0.54,
    side: TradeSide.Buy,
  },
  {
    symbol: 'XRP',
    base: 'USDT',
    amount: 1377,
    atPrice: 0.32,
    side: TradeSide.Buy,
  },
  {
    symbol: 'XTZ',
    base: 'USDT',
    amount: 245.7,
    atPrice: 4.07,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LINK',
    base: 'USDT',
    amount: 58.69,
    atPrice: 17,
    side: TradeSide.Buy,
  },
  {
    symbol: 'VET',
    base: 'USDT',
    amount: 5112,
    atPrice: 0.0197,
    side: TradeSide.Buy,
  },
  {
    symbol: 'JST',
    base: 'USDT',
    amount: 1428,
    atPrice: 0.07,
    side: TradeSide.Buy,
  },
  {
    symbol: 'THETA',
    base: 'USDT',
    amount: 500,
    atPrice: 0.419,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 90.9,
    atPrice: 0.55,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 89.3,
    atPrice: 0.56,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 87.7,
    atPrice: 0.57,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 172,
    atPrice: 0.58,
    side: TradeSide.Buy,
  },
  {
    symbol: 'LEND',
    base: 'USDT',
    amount: 336,
    atPrice: 0.59529,
    side: TradeSide.Buy,
  },
];
