# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 400 ~/.ssh/id_rsa

      - name: Setup node.js env
        uses: actions/setup-node@v1.4.3
        with:
          node-version: "${{matrix.node_version}}"

      - name: Installing node modules
        run: npm i

      - name: Building App
        run: npm run build
        env:
          CI: false

      - name: Zip build
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: ../build.zip
          directory: ./build

      - name: Deployment
        run: |
          ssh -o StrictHostKeyChecking=no -p 2233 root@tinypro.ir "rm -rf /var/www/html/cryptfolio && mkdir -p /var/www/html/cryptfolio && chown 775 /var/www/html/cryptfolio"
          echo "Removed prev folder"
          scp -o StrictHostKeyChecking=no -P 2233 ./build.zip root@tinypro.ir:/var/www/html/cryptfolio/build.zip
          echo "Copied the build.zip"
          ssh -o StrictHostKeyChecking=no -p 2233 root@tinypro.ir "unzip /var/www/html/cryptfolio/build.zip -d /var/www/html/cryptfolio/"
          echo "Unzipped the build.zip"
